project:
  type: book

book:
  title: "Employment Law"
  subtitle: Elon Law School
  author: Eric M. Fink
  date-format: MMMM YYYY
  license: "CC BY NC SA"
  page-navigation: true
  page-footer:
      center: 
        - text: "Last updated: {{< now >}}"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: envelope
        menu:
          - text: Email Prof. Fink
            href: mailto:efink@elon.edu
      - icon: calendar
        menu:
          - text: Make an appointment
            href: https://calendly.com/emfink/
      - icon: file-pdf
        menu: 
          - text: "Casebook PDF"
            href: EmploymentLawCasebook.pdf
      - icon: github
        menu:
          - text: Report an issue
            href:  https://github.com/EricMFink/EmploymentLaw/issues/new
          - text: View source code
            href:  https://github.com/EricMFink/EmploymentLaw
    collapse-level: 1
  chapters: 
    - href: index.qmd
      text: Home
    - href: syllabus.qmd
      text: Syllabus
    - part: "Casebook"
      chapters: 
        - 01-Front/frontispiece.qmd
        - 01-Front/license.qmd
        - 01-Front/epigraph.qmd
        - 01-Front/preface.qmd
        - 02-Main/chap1.qmd
        - 02-Main/chap2.qmd
        - 02-Main/chap3.qmd
        - 02-Main/chap4.qmd
        - 02-Main/chap5.qmd
        - 02-Main/chap6.qmd
        - 02-Main/chap7.qmd
        - 02-Main/chap8.qmd
        - 02-Main/chap9.qmd
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
    - part: Problems
      chapters: 
      - problems/confidentiality.qmd
      - problems/loyalty.qmd
      - problems/workers-comp.qmd

filters:
  - citetools
bibliography_fedcases: refs/fedcases.yaml
bibliography_statecases: refs/statecases.yaml
bibliography_othercases: refs/othercases.yaml
bibliography_fedstatutes: refs/fedstatutes.yaml
bibliography_statestatutes: refs/statestatutes.yaml
bibliography_otherstatutes: refs/otherstatutes.yaml
bibliography_other: refs/other.yaml
csl: refs/casebook.csl
nocite: |
  @*

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    title-block-style: none
    reference-location: margin
    citation-location: document
    toc: true
    number-sections: true
    number-depth: 2
    toc-location: left
    toc-depth: 4
    callout-icon: false
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://www.emfink.net/assets/img/favicon.ico">
        <meta name="robots" content="noarchive">